theme = "hugo-developer-portfolio"
# Base information
baseURL = "https://github.com/limyongkai/ykblog.git"
publishDir = "docs"
languageCode = "en-gb"
title = "Lim Yong Kai"
# theme = "hugo-developer-portfolio"
googleAnalytics = ""

# Remove this when using normally
# themesDir = "../../" 
# `
[module]
  [[module.imports]]
    path = "github.com/samrobbins85/hugo-developer-portfolio"

# Plugins
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "https://cdn.jsdelivr.net/npm/uikit@3.2.6/dist/css/uikit.min.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "https://cdn.jsdelivr.net/npm/uikit@3.2.6/dist/js/uikit.min.js"
  [[params.plugins.js]]
  URL = "https://cdn.jsdelivr.net/npm/uikit@3.2.6/dist/js/uikit-icons.min.js"


# navigation
[menu]

  [[menu.main]]
  name = "About"
  URL = "about"
  weight=1

  [[menu.main]]
  name = "Blog"
  URL = "blog"
  weight=2

  [[menu.main]]
  name = "Portfolio"
  URL = "portfolio"
  weight=3

 

[params]
home = "Home"
# Meta data
description = "The website of Yong Kai, Master of IT in Business student at Singapore Management University"
author = "Lim Yong Kai"


  [params.contact]
  enable = false
  formAction = "" #contact form works with formspree.io

  [params.footer]
  email = "limyongkai@gmail.com"
  address = "Singapore"
  googlemaps = "https://www.google.com/maps/embed?pb=!1m14!1m12!1m3!1d87684.31785000746!2d103.81682981405059!3d1.365007729751167!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!5e0!3m2!1sen!2ssg!4v1620838412300!5m2!1sen!2ssg"
[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    style = "rainbow_dash"
    tabWidth = 4

